apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-deployment.yaml
  - namespace.yaml
  - grafana.yaml
  - clusterrole.yaml

namespace: prometheus

configMapGenerator:
  - name: config
    files:
      - config/prometheus.rules
      - config/prometheus.yml
